Lint/UselessAssignment:
  Exclude:
    - 'spec/memoized_on_frozen_spec.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'spec/support/rectangle.rb'

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'example.rb'
    - 'vendor/**/*'
